AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Function to shutdown all untagged instances in all regions

Metadata:
  AWS::ServerlessRepo::Application:
    Name: untagged-ec2-instance-stopper
    Description: stops all instance in all region that miss a given tag
    Author: janek
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['shutdown','untagged','ec2']
    SemanticVersion: "0.0.2"
    SourceCodeUrl: https://github.com/oev-berlin/aws-untagged-intance-stopper
    HomePageUrl: https://github.com/oev-berlin/aws-untagged-intance-stopper
Parameters:
  CronPattern:
    Description: define the cron pattern (default daily at 7pm)
    Type: String
    Default: cron(0 19 * * ? *)
  TagKey:
    Description: The tag key for instances to be shut down
    Type: String
    Default: running
  TagValue:
    Description: The tag value for instances to be shut down
    Type: String
    Default: perm

Globals:
  Function:
    Timeout: 600

Resources:
  ShutdownUntaggedInstances:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: shutdown_untagged/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - Statement:
        - Sid: EC2DescribeRegions
          Effect: Allow
          Action:
          - ec2:DescribeRegions
          - ec2:DescribeInstances
          - ec2:StopInstances
          Resource: '*'
      Environment: 
        Variables:
            TAG_KEY: !Ref TagKey
            TAG_VALUE: !Ref TagValue
      Events:
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref CronPattern

Outputs:
  ShutdownUntaggedInstances:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ShutdownUntaggedInstances.Arn
  ShutdownUntaggedInstancesIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ShutdownUntaggedInstancesRole.Arn
